import { app, BrowserWindow, ipcMain } from 'electron';
import { Database } from 'sqlite';
import { openDb } from '../db/Database';
import { setDatabase } from '../db/Handlers';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Create or open the SQLite database
let db: Database;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // const scale = .864;
  const scale = .76;
  const win_height = Math.round(900*scale);
  const win_width = Math.round((1600)*scale);
  console.log(win_height)
  console.log(win_width)
  const mainWindow = new BrowserWindow({
    height: win_height,
    width: win_width,
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
    },
  });
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.webContents.openDevTools();
  // Listen for minimize, maximize, close requests
  ipcMain.on('minimize-window', () => {
    mainWindow.minimize();
  });

  ipcMain.on('maximize-window', () => {
    if (mainWindow.isMaximized()) {
      mainWindow.unmaximize();
    } else {
      mainWindow.maximize();
    }
  });

  ipcMain.on('close-window', () => {
    mainWindow.close();
  });
};

app.on('ready', async () => {
  db = await openDb();
  setDatabase(db);
  createWindow();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
